draw_set_font(fnt_start)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_color(#2e3557)
draw_text(room_width / 2, room_height / 2, title)
draw_set_color(c_white)
draw_text((room_width / 2)-4, (room_height / 2) + 4, "CRAZY\nSPACE POOL")

draw_set_font(fnt_hud)
draw_set_color(c_white)
draw_text(room_width / 2, room_height - 40, "Premi Z per iniziare")